services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ai-crm-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Shubham@123
      MYSQL_DATABASE: my_test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Shubham@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./backend/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - ai-crm-network
    command: --default-authentication-plugin=mysql_native_password

  # Spring Boot Backend
  backend:
    build: ./backend
    container_name: ai-crm-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/my_test_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Shubham@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql
    networks:
      - ai-crm-network

  # React Frontend (using Node.js directly)
  frontend:
    image: node:18-alpine
    container_name: ai-crm-frontend
    restart: unless-stopped
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-working:/app
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8080/api
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=3000
    depends_on:
      - backend
    networks:
      - ai-crm-network

volumes:
  mysql_data:
    driver: local

networks:
  ai-crm-network:
    driver: bridge
